version: "3.4"
services:
  kinesis:
    image: dlsniper/kinesalite
    ports:
      - 4567:4567
    expose:
      - 4567
  dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
      - 8000:8000
    expose:
      - 8000
  gokini:
    image: golang:1.10
    volumes:
      - .:/go/src/github.com/patrobinson/gokini
    working_dir: /go/src/github.com/patrobinson/gokini
    depends_on:
      - kinesis
      - dynamodb
    links:
      - kinesis
      - dynamodb
    environment:
      - KINESIS_ENDPOINT=http://kinesis:4567
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_DEFAULT_REGION=ap-nil-1
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
